# Chest options
chest:
  # World where the chest is generated
  world: world

# Configuration for chest contents
items:
  # Each set of loot has a unique key
  basic_loot:
    # The weight of the set (required)
    weight: 50
    # The items in the set
    items:
      iron_ingot:
        type: IRON_INGOT
        amount: 10
      bread:
        type: BREAD
        amount: 5
  rare_loot:
    weight: 10
    items:
      diamond:
        type: DIAMOND
        amount: 1
      enchanted_gold_pickaxe:
        type: GOLDEN_PICKAXE
        amount: 1
        enchantments:
          - EFFICIENCY
          - UNBREAKING
  legendary_loot:
    weight: 1
    items:
      nether_star:
        type: NETHER_STAR
      enchanted_diamond_chestplate:
        type: DIAMOND_CHESTPLATE
        enchantments:
          - PROTECTION
          - THORNS

# radious
radius: 100

# The time in seconds at which the chest should be generated
generation-time: 0